# conf/config.yaml
start_time: 0.0
snippet_gap: 0.01667  # roughly 1/60 seconds
mode: "folder"
modalities:
#  - "gaze"
#  - "imu"
#  - "rgb"
#  - "gaze+rgb"
#  - "gaze+imu"
#  - "imu+rgb"
  - "gaze+imu+rgb"
output_save_path: "output/"
root_dir: "dataset/mp4/"
file_type: "mp4"
mps_folder: "dataset/mps/"
model_name:
  - "v1_default"
#  - "v0"
num_workers: 1  # adjust based on available CPU cores
device: "cuda"  # or "cpu" if no GPU is available
